name: "TestPypi CI-CD- Contextual/graph"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python with uv
        uses: astral-sh/setup-uv@v6

      - name: Create/Activate virtual environment and install dependencies
        run: |
          uv sync --all-groups --all-extras
          source .venv/bin/activate

      - name: Install pre-commit hooks
        run: uv run pre-commit install --install-hooks

      - name: Run hooks Formaters, Linters and Static type verifiers
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest .

      - name: Build
        run: uv build

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
